src/main/java/com/wipro/app/msr/controller/businessleader/IBusinessLeaderController.java
package com.wipro.app.msr.controller.businessleader;

import com.wipro.app.msr.generic.controller.IBaseController;

public interface IBusinessLeaderController extends IBaseController<BusinessLeader, Integer> {
	
}

src/main/java/com/wipro/app/msr/sow/controller/ISowController.java
package com.wipro.app.msr.sow.controller;

import com.wipro.app.msr.generic.controller.IBaseController;
import com.wipro.app.msr.sow.Sow;

public interface ISowController extends IBaseController<Sow, Integer> {
	
	

}

src/main/java/com/wipro/app/msr/web/ProjectFacesBean.java
package com.wipro.app.msr.web;

import java.util.ArrayList;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.convert.Converter;
import javax.faces.model.SelectItem;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import com.wipro.app.msr.controller.ControllerFacade;
import com.wipro.app.msr.generic.web.BaseFacesBean;
import com.wipro.app.msr.project.Project;
import com.wipro.app.msr.sow.Sow;
import com.wipro.app.msr.util.constants.Messages;
import com.wipro.app.msr.util.exceptions.ControllerException;

@Controller
@Scope("session")
@ManagedBean(name = "projectFacesBean")
public class ProjectFacesBean extends BaseFacesBean<Project> {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1443064834350590375L;

	@Autowired
	private ControllerFacade facade;
	
	private List<SelectItem> sowList;
	

	public ProjectFacesBean() {
		super("project");
		item = new Project();
	}

	public void clean() {
		try {
			list = facade.getProjectController().selectAll();
		} catch (ControllerException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	public String save() {
		try {
			if (item.getId() == null) {
				facade.getProjectController().insert(item);
			} else {
				facade.getProjectController().update(item);
			}
			addMessage(FacesMessage.SEVERITY_INFO, Messages.ITEM_SUCCESS, "Project");
			item = new Project();
			clean();
			return getListPath();
		} catch (ControllerException e) {
			addWebMessage(e);
		}

		return null;
	}

	public String add() {
		action = "Add";
		item = new Project();
		return getFormPath();
	}

	public String edit(Project row) {
		action = "Edit";
		item = row;
		return getFormPath();
	}

	public String cancel() {
		action = "";
		item = new Project();
		return getListPath();
	}
	
	public void delete(Project row) {		
		try {				
			facade.getProjectController().delete(row.getId());				
			addMessage(FacesMessage.SEVERITY_INFO, Messages.ITEM_REMOVE_SUCCESS, "Project");	
			clean();
		} catch (ControllerException e) {
			addWebMessage(e);
		}
		
	}
	
	public List<SelectItem> listSow() {
		try {
			this.sowList = new ArrayList<SelectItem>();
			this.sowList.add(new SelectItem(null,"..."));
			List<Sow> sowList = facade.getSowController().selectAll();
			for (Sow sow : sowList) {
				this.sowList.add(new SelectItem(sow, sow.getName()));
			}
			return this.sowList;
		} catch (ControllerException e) {
			addWebMessage(e);
		}
		return null;
	}
	
	
	public Converter getSowConverter() {
		return getEntityConverter(Sow.class, "sow");
	}
	
}

src/main/java/com/wipro/app/msr/web/StoryFacesBean.java
package com.wipro.app.msr.web;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.model.SelectItem;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import com.wipro.app.msr.alm.ALMFilter;
import com.wipro.app.msr.alm.ALMStory;
import com.wipro.app.msr.alm.FilterTypeEnum;
import com.wipro.app.msr.controller.ControllerFacade;
import com.wipro.app.msr.controller.businessleader.BusinessLeader;
import com.wipro.app.msr.controller.resource.Resource;
import com.wipro.app.msr.controller.story.Story;
import com.wipro.app.msr.generic.web.BaseFacesBean;
import com.wipro.app.msr.job.StoryJob;
import com.wipro.app.msr.user.User;
import com.wipro.app.msr.util.constants.Messages;
import com.wipro.app.msr.util.constants.RoleEnum;
import com.wipro.app.msr.util.constants.TicketStatusEnum;
import com.wipro.app.msr.util.constants.UserStatusEnum;
import com.wipro.app.msr.util.exceptions.ControllerException;

@Controller
@Scope("session")
@ManagedBean(name = "storyFacesBean")
public class StoryFacesBean extends BaseFacesBean<Story> {

	private static final long serialVersionUID = 1L;

	@Autowired
	private ControllerFacade facade;
	
	private List<SelectItem> status;
	private List<SelectItem> businessLeaders;
	private List<SelectItem> resources;
	private List<SelectItem> roles;
	private Date startDate;
	private Date endDate;
	private SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
	private User loggedUser;
	private List<ALMStory> almStories;
	private ALMFilter almFilter;
	private List<SelectItem> almFilterTypeList;

	public StoryFacesBean() {
		super("story");
		item = new Story();
		filter = new Story();
		setDefaultDates();		
		almStories = new ArrayList<ALMStory>();
		almFilter = new ALMFilter();
	}
	
	private User getUser() {
		if(loggedUser == null){		
			String userName = FacesContext.getCurrentInstance().getExternalContext().getUserPrincipal().getName();
			try {
				loggedUser = facade.getUserController().getUserByLogin(userName);
			} catch (ControllerException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
		return loggedUser;

	}

	private void setResourceDefault() {
		Resource resource = getUser().getResource();
		if (resource != null) {
			item.setResource(resource);
		}

	}

	private void setDefaultDates() {
		Calendar calendar = GregorianCalendar.getInstance();
		int month = calendar.get(Calendar.MONTH);
		Calendar calendarStartDate = GregorianCalendar.getInstance();
		calendarStartDate.set(Calendar.MONTH, month - 1);
		calendarStartDate.set(Calendar.DAY_OF_MONTH, 25);
		startDate = calendarStartDate.getTime();
		Calendar calendarEndDate = GregorianCalendar.getInstance();
		calendarEndDate.set(Calendar.DAY_OF_MONTH, 25);
		endDate = calendarEndDate.getTime();

	}

	public void filter() {
		try {
			if (filter.getNumber() != null) {
				if (filter.getNumber().isEmpty()) {
					filter.setNumber(null);
				} else {
					filter.setNumber(filter.getNumber().trim());
				}
			}
			if (filter.getRole() == RoleEnum.NONE) {
				filter.setRole(null);
			}
			if (filter.getStatus() == TicketStatusEnum.NONE) {
				filter.setStatus(null);
			}
			filter.setStartDate(simpleDateFormat.format(startDate));
			filter.setEndDate(simpleDateFormat.format(endDate));
			setDefaultUserFilter();
			list = facade.getStoryController().selectBy(filter);
		} catch (ControllerException e) {
			e.printStackTrace();
		}
	}

	public void clean() {
		filter = new Story();
		setDefaultDates();
		filter();
	}
	
	public void cleanAlmStories(){
		almStories = new ArrayList<ALMStory>();
		almFilter = new ALMFilter(); 
		
	}
	
	public void filterAlmStories() {
		try {
			almStories = facade.getStoryController().getALMStories(almFilter);
			if(getLoggedUser() != null){
				for (ALMStory almStory : almStories) {
					almStory.setBusinessLeader(getLoggedUser().getResource().getBusinessLeader());
					almStory.setRole(getLoggedUser().getResource().getRole());
					almStory.setResource(getLoggedUser().getResource());
				}
			}
		} catch (ControllerException e) {
			e.printStackTrace();
		}
	}	

	public List<SelectItem> listStatus() {
		this.status = new ArrayList<SelectItem>();
		for (TicketStatusEnum status : TicketStatusEnum.values()) {
			this.status.add(new SelectItem(status, status.toString()));
		}
		return this.status;
	}

	public List<SelectItem> listRoles() {
		this.roles = new ArrayList<SelectItem>();
		for (RoleEnum role : RoleEnum.values()) {
			this.roles.add(new SelectItem(role, role.toString()));
		}
		return this.roles;
	}
	
	public List<SelectItem> listAlmFilterType() {
		this.almFilterTypeList = new ArrayList<SelectItem>();
		for (FilterTypeEnum filter : FilterTypeEnum.values()) {
			this.almFilterTypeList.add(new SelectItem(filter, filter.toString()));
		}
		return this.almFilterTypeList;
	}
	

	public List<SelectItem> listResources() {
		try {
			this.resources = new ArrayList<SelectItem>();
			this.resources.add(new SelectItem(null, "..."));
			Resource filter = new Resource();
			filter.setStatus(UserStatusEnum.ACTIVE);
			List<Resource> resourceList = facade.getResourceController().selectBy(filter);
			for (Resource resource : resourceList) {
				this.resources.add(new SelectItem(resource, resource.getName()));
			}

			setResourceDefault();

			return this.resources;

		} catch (ControllerException e) {
			e.printStackTrace();
		}

		return null;
	}

	public List<SelectItem> listBusinessLeaders() {
		try {
			this.businessLeaders = new ArrayList<SelectItem>();
			this.businessLeaders.add(new SelectItem(null, "..."));
			List<BusinessLeader> businessLeadersList = facade.getBusinessLeaderController().selectAll();
			for (BusinessLeader businessLeader : businessLeadersList) {
				this.businessLeaders.add(new SelectItem(businessLeader, businessLeader.getName()));
			}
			return this.businessLeaders;
		} catch (ControllerException e) {
			addWebMessage(e);
		}
		return null;
	}

	public String add() {
		action = "Add";
		item = new Story();		
		if (filter.getResource() != null) {
			item.setResource(filter.getResource());
			// CHANGE
			item.setPoints(0);
			item.setStatus(TicketStatusEnum.COMPLETED);
		}
		cleanAlmStories();
		return getFormPath();
	}

	public String edit(Story row) {
		action = "Edit";
		item = row;
		return getFormPath();
	}

	public String cancel() {
		action = "";
		item = new Story();
		return getListPath();
	}

	public String save() {
		if (validate(item)) {
			try {
				item.setNumber(item.getNumber().trim());
				if (item.getId() == null) {
					facade.getStoryController().insert(item);
				} else {
					facade.getStoryController().update(item);
				}
				addMessage(FacesMessage.SEVERITY_INFO, Messages.ITEM_SUCCESS, "Story");
				item = new Story();
				filter();
				return getListPath();
			} catch (ControllerException e) {
				addWebMessage(e);
			}
		}
		return null;
	}

	private boolean validate(Story story) {
		boolean valid = true;
		if (story.getNumber() == null || story.getNumber().trim().equals("")) {
			addMessage(FacesMessage.SEVERITY_ERROR, Messages.INVALID_FIELD, "Number");
			valid = false;
		}
		if (story.getPoints() == null || story.getNumber().trim().equals("")) {
			addMessage(FacesMessage.SEVERITY_ERROR, Messages.INVALID_FIELD, "Points");
			valid = false;
		}
		if (story.getDate() == null) {
			addMessage(FacesMessage.SEVERITY_ERROR, Messages.INVALID_FIELD, "Date");
			valid = false;
		}
		if (story.getStatus() == null || story.getStatus() == TicketStatusEnum.NONE) {
			addMessage(FacesMessage.SEVERITY_ERROR, Messages.INVALID_FIELD, "Status");
			valid = false;
		}
		if (story.getResource() == null) {
			addMessage(FacesMessage.SEVERITY_ERROR, Messages.INVALID_FIELD, "Resource");
			valid = false;
		}
		/*
		 * if (valid && action.equals("Add")) { try { List<Story> listFiltered =
		 * facade.getStoryController().selectBy(item); if
		 * (!listFiltered.isEmpty()) { addMessage(FacesMessage.SEVERITY_ERROR,
		 * Messages.DUPLICATED_ITEM, item.getNumber(),
		 * item.getResource().getName()); valid = false; } } catch
		 * (ControllerException e) { e.printStackTrace(); } }
		 */
		return valid;
	}

	public Converter getResourceConverter() {
		return getEntityConverter(Resource.class, "resource");
	}

	public Converter getBusinessLeaderConverter() {
		return getEntityConverter(BusinessLeader.class, "business-leader");
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	private void setDefaultUserFilter() {
		if(getUser() != null){		
			if("USER".equals(getUser().getRole())){
				Resource resource = getUser().getResource();
				if (resource != null) {
					filter.setResource(resource);
					filter.setBusinessLeader(resource.getBusinessLeader());
				}	
			}
		}		
	}

	public User getLoggedUser() {
		return loggedUser;
	}

	public void setLoggedUser(User loggedUser) {
		this.loggedUser = loggedUser;
	}

	public List<ALMStory> getAlmStories() {
		return almStories;
	}

	public void setAlmStories(List<ALMStory> almStories) {
		this.almStories = almStories;
	}

	public ALMFilter getAlmFilter() {
		return almFilter;
	}

	public void setAlmFilter(ALMFilter almFilter) {
		this.almFilter = almFilter;
	}

	public List<SelectItem> getAlmFilterTypeList() {
		return almFilterTypeList;
	}

	public void setAlmFilterTypeList(List<SelectItem> almFilterTypeList) {
		this.almFilterTypeList = almFilterTypeList;
	}	
	
	public String copyStories() {

src/main/java/com/wipro/app/msr/web/UserFacesBean.java
package com.wipro.app.msr.web;

import java.util.ArrayList;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.model.SelectItem;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import com.wipro.app.msr.controller.ControllerFacade;
import com.wipro.app.msr.controller.resource.Resource;
import com.wipro.app.msr.generic.web.BaseFacesBean;
import com.wipro.app.msr.user.User;
import com.wipro.app.msr.util.PasswordEncoderGenerator;
import com.wipro.app.msr.util.constants.Messages;
import com.wipro.app.msr.util.constants.UserStatusEnum;
import com.wipro.app.msr.util.exceptions.ControllerException;

@Controller
@Scope("session")
@ManagedBean(name = "userFacesBean")
public class UserFacesBean extends BaseFacesBean<User> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2180485044325012093L;
	
	@Autowired
	private ControllerFacade facade;	
	
	private List<SelectItem> resources;
	
	private List<SelectItem> status;
	
	private List<SelectItem> roles;
	
	private String confirmPassword;
	
	public UserFacesBean() {
		super("user");
		item = new User();
		item.setStatus(true);
	}
	
	public void clean() {
		try {
			list = facade.getUserController().selectAll();
		} catch (ControllerException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	public List<SelectItem> listStatus() {
		this.status = new ArrayList<SelectItem>();
		this.status.add(new SelectItem(true, UserStatusEnum.ACTIVE.getName()));
		this.status.add(new SelectItem(false, UserStatusEnum.INACTIVE.getName()));		
		return this.status;
	}
	
	public List<SelectItem> listRoles() {
		this.roles = new ArrayList<SelectItem>();		
		this.roles.add(new SelectItem("SUPER_USER", "Super User"));
		this.roles.add(new SelectItem("REVIEWER", "Reviewer"));
		this.roles.add(new SelectItem("USER", "User"));
		this.roles.add(new SelectItem("MANAGER", "Manager"));
		return this.roles;
	}
	
	
	public List<SelectItem> listResources() {
		try {
			this.resources = new ArrayList<SelectItem>();
			this.resources.add(new SelectItem(null,"..."));
			List<Resource> resourceList = facade.getResourceController().selectAll();
			for (Resource resource : resourceList) {
				this.resources.add(new SelectItem(resource, resource.getName()));
			}
			
			return this.resources;
			
		} catch (ControllerException e) {
			e.printStackTrace();
		}
		
		return null;
	}

	public String getConfirmPassword() {
		return confirmPassword;
	}

	public void setConfirmPassword(String confirmPassword) {
		this.confirmPassword = confirmPassword;
	}
	
	public String save() {		
			try {
				if (item.getId() == null) {
					item.setPassword(PasswordEncoderGenerator.encodePassword(item.getPassword()));
					facade.getUserController().insert(item);
				} else {					
					facade.getUserController().update(item);
				}
				addMessage(FacesMessage.SEVERITY_INFO, Messages.ITEM_SUCCESS, "User");
				item = new User();
				clean();
				return getListPath();
			} catch (ControllerException e) {
				addWebMessage(e);
			}
		
		return null;
	}
	
	public String add() {
		action = "Add";
		item = new User();
		return getFormPath();
	}

	public String edit(User row) {
		action = "Edit";
		item = row;
		return getFormPath();
	}

	public String cancel() {
		action = "";
		item = new User();
		return getListPath();
	}
	
	public Converter getResourceConverter() {
		return getEntityConverter(Resource.class, "resource");
	}

	public void delete(User row) {		
		try {				
			facade.getUserController().delete(row.getId());				
			addMessage(FacesMessage.SEVERITY_INFO, Messages.ITEM_REMOVE_SUCCESS, "User");	
			clean();
		} catch (ControllerException e) {
			addWebMessage(e);
		}
		
	}
	
	public void resetPassword(User row) {
		
		try {
			row.setPassword(PasswordEncoderGenerator.encodePassword("123456"));
			facade.getUserController().update(row);			
			FacesMessage facesMsg = new FacesMessage(FacesMessage.SEVERITY_INFO,"","Password reseted.");
			FacesContext.getCurrentInstance().addMessage(null, facesMsg);
			
		} catch (ControllerException e) {			
			FacesMessage facesMsg = new FacesMessage(FacesMessage.SEVERITY_ERROR, "Error", "Reset Password failed");
			FacesContext.getCurrentInstance().addMessage(null, facesMsg);
		}
		
	}
	
	
}

src/main/webapp/pages/business-leader-form.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	template="/template/template.xhtml">

	<ui:param name="facesBean" value="#{businessLeaderFacesBean}" />

	<ui:define name="content">
		<h:form id="form">
			<p:messages id="messages" showDetail="true" autoUpdate="true" />
			<h:outputText value="Business Leader : #{facesBean.action}" styleClass="breadcrumb"/>
			<br /><br />
			<h:panelGrid columns="2" cellpadding="5" cellspacing="3">
				<p:outputLabel value="Name: *"/>
				<p:inputText value="#{facesBean.item.name}" />
				<p:outputLabel value="Sow: *" />
				<p:selectOneMenu value="#{facesBean.item.sow}" converter="#{facesBean.sowConverter}">
					<f:selectItems value="#{facesBean.listSow()}" />
				</p:selectOneMenu>
				<p:outputLabel value="Status: *" />
				<p:selectOneMenu id="combo" value="#{facesBean.item.status}" converter="#{facesBean.enumConverter}">
					<f:selectItems value="#{facesBean.listStatus()}" />
				</p:selectOneMenu>
			</h:panelGrid>
			<br /><br />
			<p:commandButton action="#{facesBean.save}" icon="ui-icon-disk" value="Save" />
			<p:commandButton action="#{facesBean.cancel}" icon="ui-icon-close" value="Cancel" />
		</h:form>
	</ui:define>

</ui:composition>

src/main/webapp/pages/change-password.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:sec="http://www.springframework.org/security/tags"
	template="/template/template.xhtml">
	
	<ui:define name="content">
		<h:form id="form">
			<p:messages id="messages" showDetail="true" autoUpdate="true" />
			<h:outputText value="Change Password" class="breadcrumb" />				
			<br /><br />
			<h:panelGrid columns="2" cellpadding="5" cellspacing="3">
				<h:outputLabel for="pwd1" value="New Password: *" />
		        <p:password id="pwd1" value="#{loginController.newPassword}" match="pwd2" label="New Password" required="true" />
		 
		        <h:outputLabel for="pwd2" value="Confirm Password: *" />
		        <p:password id="pwd2" value="#{loginController.confirmPassword}" label="Confirm Password" required="true" />			
			</h:panelGrid>
			<br /><br />
			<p:commandButton action="#{loginController.changePassword}" icon="ui-icon-disk" value="Save" />
			<p:commandButton action="#{loginController.cancel}" icon="ui-icon-close" value="Cancel" />
		</h:form>
	</ui:define>

</ui:composition>

src/main/webapp/pages/story.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	template="/template/template.xhtml">

	<ui:param name="facesBean" value="#{storyFacesBean}" />

	<ui:define name="content">
		<h:form id="form">
			<p:messages id="messages" showDetail="true" autoUpdate="true" />
			<h:outputText value="Story" styleClass="breadcrumb"/>
			<br /><br />
			<p:fieldset legend="Filter" class="filter" id="filter">
				<h:panelGrid columns="2" cellpadding="5" cellspacing="3">
					<p:outputLabel value="Start Date: *" />
					<p:calendar value="#{facesBean.startDate}" pattern="MMM dd yyyy"/>
					<p:outputLabel value="End Date: *" />
					<p:calendar value="#{facesBean.endDate}" pattern="MMM dd yyyy"/>
					<p:outputLabel value="Number: " />
					<p:inputText value="#{facesBean.filter.number}" />
					<p:outputLabel value="Status: " />
					<p:selectOneMenu value="#{facesBean.filter.status}" converter="#{facesBean.enumConverter}">
						<f:selectItems value="#{facesBean.listStatus()}" />
					</p:selectOneMenu>
					<p:outputLabel value="Resource " />
					<p:selectOneMenu value="#{facesBean.filter.resource}" converter="#{facesBean.resourceConverter}" disabled="#{sec:areNotGranted('SUPER_USER,REVIEWER,MANAGER')}">
						<f:selectItems value="#{facesBean.listResources()}" />
					</p:selectOneMenu>
					<p:outputLabel value="Role: " />
					<p:selectOneMenu value="#{facesBean.filter.role}" converter="#{facesBean.enumConverter}">
						<f:selectItems value="#{facesBean.listRoles()}" />
					</p:selectOneMenu>
					<p:outputLabel value="Business Leader: " />
					<p:selectOneMenu value="#{facesBean.filter.businessLeader}" converter="#{facesBean.businessLeaderConverter}" disabled="#{sec:areNotGranted('SUPER_USER,REVIEWER,MANAGER')}">
						<f:selectItems value="#{facesBean.listBusinessLeaders()}" />
					</p:selectOneMenu>
				</h:panelGrid>
				<br/><br/>
				<p:commandButton actionListener="#{facesBean.filter}" icon="ui-icon-search" value="Search" update="table, total" ajax="true"/>
				<p:commandButton actionListener="#{facesBean.clean}" icon="ui-icon-close" value="Clean" update="table, filter, total"/>				
			</p:fieldset>
			<br />
			<p:commandButton action="#{facesBean.add}" icon="ui-icon-plus" title="Add" styleClass="add-button"/>
			<h:outputText value="Total: #{facesBean.list.size()} records" styleClass="total" id="total"/>
			<p:dataTable var="story" value="#{facesBean.list}" id="table"> 
				<p:column headerText="" class="center" style="width: 10%">
					<p:commandButton action="#{facesBean.edit(story)}" icon="ui-icon-pencil" title="Edit" />
				</p:column>
				<p:column headerText="NUMBER" class="center" sortBy="#{story.number}" style="width:10%">
					<h:outputText value="#{story.number}" />
				</p:column>
				<p:column headerText="DATE" class="center" sortBy="#{story.date}" style="width:10%">
					<h:outputText value="#{story.date}" >
						<f:convertDateTime pattern="MM/dd/yyyy" />
					</h:outputText>
				</p:column>
				<p:column headerText="STATUS" class="center" sortBy="#{story.status}" style="width:20%" >
					<h:outputText value="#{story.status.name}" />
				</p:column>
				<p:column headerText="POINTS" class="center" sortBy="#{story.points}" style="width:10%" >
					<h:outputText value="#{story.points}" />
				</p:column>
				<p:column headerText="RESOURCE" sortBy="#{story.resource.name}" style="width:30%" >
					<h:outputText value="#{story.resource.name}" />
				</p:column>
				<p:column headerText="ROLE" sortBy="#{story.role.name}" style="width:20%" class="center">
					<h:outputText value="#{story.role.name}" />
				</p:column>
				<p:column headerText="BUSINESS LEADER" sortBy="#{story.businessLeader.name}" style="width:30%" >
					<h:outputText value="#{story.businessLeader.name}" />
				</p:column>
				<p:column headerText="" style="width:5%" >
					<p:commandButton action="#{facesBean.delete(story)}" rendered="#{sec:areAnyGranted('SUPER_USER')}" ajax="true" update="table" icon="ui-icon-trash" title="Delete" styleClass="add-button"/>
				</p:column>
			</p:dataTable>
		</h:form>
	</ui:define>


</ui:composition>